name: LogUtility Trigger
on:
  push:
    branches: [master]
    #paths: 'logs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get File
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Output
        id: out
        run: >-
          echo "::set-output name=sellerid::$(
            id=${{ steps.files.outputs.all }} |
            echo "${id}" | 
            awk -F '/' '{print $2}'
          )"
      - name: Trigger LogUtility
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.ACTIONS_TOKEN}}
          repository: tanya-ondc/log-verification-utility 
          event-type: Trigger LogUtility
          client-payload: '{"ref": "${{ steps.out.outputs.sellerid }}"}'
          
