name: LogUtility Trigger
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger LogUtility
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.ACTIONS_TOKEN}}
          repository: tanya-ondc/log-verification-utility 
          event-type: Trigger LogUtility
      - name: Get File
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          for change_file in ${{ steps.files.outputs.all }}; do
            echo "${change_file}" | awk -F '/' '{print $2}'
          done
          id=${{ steps.files.outputs.all }}[0]
          echo "${id}" | awk -F '/' '{print $2}'
