name: LogUtility Trigger
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger LogUtility
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.ACTIONS_TOKEN}}
          repository: tanya-ondc/log-verification-utility 
          event-type: Trigger LogUtility
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
