name: LogUtility Trigger
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger LogUtility
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.ACTIONS_TOKEN}}
          repository: tanya-ondc/log-verification-utility 
          event-type: Trigger LogUtility
      - name: Output results
        run: echo "${{ github.event.commits }}"
          #echo "Found ${{ inputs }}"
          #for i in ${{ steps.pl.outputs.paths }}; do
          #echo $i
          #done
